# Generated by Django 2.0 on 2020-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regions_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
