# Generated by Django 2.0 on 2020-01-12 11:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_offer', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=11)),
                ('is_new', models.BooleanField(default=False)),
                ('html_content', ckeditor.fields.RichTextField(blank=True)),
                ('time_work', models.CharField(max_length=50)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('dt_stop', models.DateTimeField()),
                ('is_fake', models.BooleanField(default=False)),
                ('ext_ident', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Category')),
                ('discount', models.ForeignKey(blank=True, db_column='discount', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Discounts')),
                ('region', models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Regions')),
                ('town', models.ForeignKey(blank=True, db_column='town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Towns')),
            ],
        ),
    ]
