# Generated by Django 2.0 on 2020-01-13 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_discounts_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'User balances',
            },
        ),
        migrations.CreateModel(
            name='BalanceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value_from', models.IntegerField()),
                ('value_to', models.IntegerField()),
                ('n_level', models.IntegerField()),
                ('image', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Level settings',
            },
        ),
        migrations.CreateModel(
            name='TypesIncomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=60)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Type of incomes',
            },
        ),
        migrations.CreateModel(
            name='UserBalanceMovements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_income', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='core.TypesIncomes')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categories'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balances',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.BalanceType'),
        ),
        migrations.AddField(
            model_name='balances',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.LevelMap'),
        ),
    ]
