# Generated by Django 2.0 on 2020-01-18 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20200118_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBalanceMovements',
            new_name='BalanceMovements',
        ),
    ]
