# Generated by Django 2.0 on 2020-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200119_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='html_content',
            field=models.CharField(max_length=16000),
        ),
    ]
