# Generated by Django 2.0 on 2020-01-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200119_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='dt_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='dt_expiration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
