# Generated by Django 2.0 on 2020-01-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200119_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='dt_expiration',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
