# Generated by Django 2.0 on 2020-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200120_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='dt_expiration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
