# Generated by Django 2.0 on 2020-01-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_offers_dt_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='dt_stop',
        ),
        migrations.AlterField(
            model_name='offers',
            name='dt_expiration',
            field=models.DateTimeField(),
        ),
    ]
