# Generated by Django 2.0 on 2020-01-22 22:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20200122_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_content', ckeditor.fields.RichTextField(blank=True, max_length=512)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(db_column='offer', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Offers')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comments',
            },
        ),
    ]
