# Generated by Django 2.0 on 2020-01-22 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_offercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offercomments',
            name='user',
        ),
        migrations.AddField(
            model_name='offercomments',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
