# Generated by Django 2.0 on 2020-01-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200123_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercomments',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Offers'),
        ),
    ]
