# Generated by Django 2.0 on 2020-01-22 23:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20200123_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('html_content', ckeditor.fields.RichTextField(max_length=4096)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Offers')),
            ],
            options={
                'verbose_name': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='OfferReviewsComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_content', ckeditor.fields.RichTextField(blank=True, max_length=1000)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OfferReviews')),
            ],
            options={
                'verbose_name': 'Review comments',
            },
        ),
        migrations.CreateModel(
            name='OfferReviewsRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Types of rates',
            },
        ),
        migrations.AddField(
            model_name='offerreviewsrates',
            name='rate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.RateType'),
        ),
        migrations.AddField(
            model_name='offerreviewsrates',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OfferReviews'),
        ),
    ]
