# Generated by Django 2.0 on 2020-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_section_topic_topiccomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
