# Generated by Django 2.0 on 2020-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_profile_is_fake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
