# Generated by Django 2.0 on 2020-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200124_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='html_content',
            field=models.CharField(max_length=50000),
        ),
    ]
