# Generated by Django 2.0 on 2020-01-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200126_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_want_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
