# Generated by Django 2.0 on 2020-03-13 18:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20200127_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('start_price', models.IntegerField()),
                ('current_price', models.IntegerField(null=True)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('dt_expiration', models.DateTimeField()),
                ('secret_key', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Auction',
            },
        ),
        migrations.CreateModel(
            name='AuctionBets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Auction')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bets',
            },
        ),
        migrations.CreateModel(
            name='OfferStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
        migrations.CreateModel(
            name='OfferTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ident', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('solved', models.BooleanField(default=False)),
                ('dt_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='ResortMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Resort')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResortType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Типы обращений',
            },
        ),
        migrations.CreateModel(
            name='ResourceTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='resource_forum/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='ResourceTopicComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ResourceTopic')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic comment',
            },
        ),
        migrations.CreateModel(
            name='ResourceTopicStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ResourceTopic')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
        migrations.CreateModel(
            name='SectionResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Section resources forum',
            },
        ),
        migrations.CreateModel(
            name='SectionResourceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
        migrations.AddField(
            model_name='balancemovements',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerreviews',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='offers',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', '남성'), ('w', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='levelmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='level/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='dt_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='dt_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='topicstatistic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Topic'),
        ),
        migrations.AddField(
            model_name='sectionresource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.SectionResourceType'),
        ),
        migrations.AddField(
            model_name='reviewstatistic',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.OfferReviews'),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.SectionResource'),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resort',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ResortType'),
        ),
        migrations.AddField(
            model_name='resort',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerstatistic',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Offers'),
        ),
        migrations.AddField(
            model_name='auction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Offers'),
        ),
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='user_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offers',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OfferTypes'),
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.SectionType'),
        ),
    ]
