# Generated by Django 2.0 on 2020-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_levelmap_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='level/%Y/%m/%d'),
        ),
    ]
